### ISSUE TITLE
Update `outputs` to reflect org subdomain

### ISSUE THREAD

**Issue by slibby** [dannykrouk/gisenterprisereporter#10]
The outputs for an Online reports include several items that do not reflect the org subdomain properly - they say `www_arcgis_com` instead of `dbsne_maps_arcgis_com` in my case. 

![image](https://github.com/dannykrouk/gisenterprisereporter/assets/1691225/97f3a8d6-7b60-4ac7-b01f-432db63b8af6)

If easy, it'd be great to be consistent on these.

**Comment by dannykrouk** [comment]
@slibby Thanks, Sam.  I'll add that to the list of things to sort out.

**Comment by dannykrouk** [comment]
Fixed in 4.0.32 (released soon)
