### ISSUE TITLE
User output doesn't accurately report storageUsage

### ISSUE THREAD

**Issue by tpcolson** [dannykrouk/gisenterprisereporter#5]
User output doesn't accurately report storageUsage, I get the same value for all users 215085652612

**Comment by tpcolson** [comment]
Any update on when this will be fixed?

**Comment by dannykrouk** [comment]
@tpcolson Are you saying that ArcGIS Enterprise does not report the correct values or that GIS Enterprise Reporter does not report the values that appear in the target ArcGIS Enterprise?  Please reach out to me via email (dkrouk@esri.com) to continue to explore.
