### ISSUE TITLE
Machine Information Reporter Warning and Error

### ISSUE THREAD

**Issue by mtorres-esri-co** [dannykrouk/gisenterprisereporter#8]
Trying to use minfo.exe, I get next warning message when I add a machine:

"... is collectable via RemoteWmi with the following note: Unable to use WinRM"

Later, when I Execute tool I get this error message:

"Problem recording machine information for mtorres
ERROR: No method worked and there was no specific method exception returned
ERROR:    at gis_enterprise_reporter.MachineInfoGetter.GetAllMachineInfoInParallel2(DataTable& resourceDataTable, DataTable& softwareDataTable, DataTable& servicesDataTable, DataTable& scheduledTaskDataTable, ResultMethod& methodUsed, ResultInfo[]& resultInfoArray) in C:\source\gis_enterprise_reporter_solution\gis_enterprise_reporter\MachineInfoGetter.cs:line 94
   at gis_enterprise_reporter.miGetterControler.GetMachineInfo() in C:\source\gis_enterprise_reporter_solution\gis_enterprise_reporter\miGetterControler.cs:line 283
PROCESSING COMPLETE"

Any ideas to solve this issue?

**Comment by mtorres-esri-co** [comment]
Running "winrm quickconfig" and answering yes to all the questions, the first warning message disappears but now the error message is this:
"RROR: No method worked and there was no specific method exception returned
ERROR:    at gis_enterprise_reporter.MachineInfoGetter.GetAllMachineInfoInParallel2(DataTable& resourceDataTable, DataTable& softwareDataTable, DataTable& servicesDataTable, DataTable& scheduledTaskDataTable, ResultMethod& methodUsed, ResultInfo[]& resultInfoArray) in C:\source\gis_enterprise_reporter_solution\gis_enterprise_reporter\MachineInfoGetter.cs:line 94
   at gis_enterprise_reporter.miGetterControler.GetMachineInfo() in C:\source\gis_enterprise_reporter_solution\gis_enterprise_reporter\miGetterControler.cs:line 283
PROCESSING COMPLETE"

**Comment by dannykrouk** [comment]
@mtorres-esri-co I'm sorry about the problem.  I'm not sure about the original error ... which seems to indicate that Remote WMI will work and then says that neither method works.  But, in the second case, neither method working indicates a lack of environment support for the two ways for GIS Enterprise Reporter to get machine information (assuming the executing user doesn't have a privileges issue).  If those methods aren't available for the target machines, there is no way to get the information.  winrm quickconfig would address one of many foundational elements that would need to be in place.  Maybe this is a circumstance to ask the network admins if they support these methods between these machines.  If they do, then there is question of why it isn't working.  But, if they do not, there is no point trying to make it work.   If you want to explore in more detail, you can email me at dkrouk@esri.com.
