### ISSUE TITLE
Cache size for tiled services

### ISSUE THREAD

**Issue by slibby** [dannykrouk/gisenterprisereporter#9]
Adding a report on the size of cache for tiled services would be excellent, unless it's already there and I couldn't find it! I don't know what the right REST API method is for this, but can do some research.

**Comment by dannykrouk** [comment]
@slibby If you're volunteering to find the relevant API call with the size information you'd like, I'm happy to make use of it and improve GIS Enterprise Reporter this way. :-)

**Comment by slibby** [comment]
I don't think there's a REST method to do this - so we can ignore it for now, unfortunately. We could do it for a .tpkx if one was uploaded, but not for map services that were then cached on the server.
